### ISSUE TITLE
[streaming stops working]

### ISSUE THREAD

**Issue by NikosApikos** [exelix11/SysDVR#226] opened 2023-04-18 21:52 UTC
I was using the older version and worked great in USB mode with 60 fps. I updated both client and switch app and now for some reason in mid game the client stops streaming and I need to relaunch it.

**Comment by Nazgile94** [comment] 2023-04-19 02:39
+1
Same 
16.0.1 latest Atmos
Switch OLED

**Comment by exelix11** [comment] 2023-04-19 09:04
Does the same happen without 60fps ? Do you get any specific error ?

**Comment by exelix11** [comment] 2023-04-19 10:33
Try 30 fps and let me know if that happens, helps to pinpoint the root cause.

**Comment by Nazgile94** [comment] 2023-04-19 10:49
30fps Wireless with Client botw freeze (Sound Still works)

**Comment by exelix11** [comment] 2023-04-19 11:10
Your seems to be a different issue since it's over network, do you get any errors on the pc ?

**Comment by exelix11** [comment] 2023-04-30 13:08
This is now fixed in latest release

**Closed by exelix11** 2023-04-30 13:08 UTC

**Comment by Nazgile94** [comment] 2023-04-30 17:28
Works !!! Ty for this fix :)
