### ISSUE TITLE
[Bug] Is it true that USB connection is better than wireless network?

### ISSUE THREAD

**Issue by tallguess** [exelix11/SysDVR#83] opened 2020-09-28 10:38 UTC
For example, I used to stream the network stream to OBS live broadcasting, but found that the picture quality was not good. Today, I tried to connect USB with the USB 3.0 interface of MacBook, but found that the jamming was so bad that it was better to use wireless network streaming.

**Comment by exelix11** [comment] 2020-09-28 10:54
In theory USB should be better because of no interferences and no random delay spikes, in practice it depends. 
The overall bandwidth is relatively low as the stream is just 720p. in my tests wifi with good signal reception will perform as well as USB.
Main concern is that getting USB to work is tricky, some people have issues with it and it's very hard to find the problem as it may be the cables (usb C being a mess), a software misconfiguration or just some kind of hardware incompatibility. If you look in the issue tracker there still are some issues i couldn't figure out nor reproduce that didn't happen when the user switched to a different PC.
Network mode on the opposite just boils down to get the right IP address and will work without issues, yes there's wifi being inconsistent but in my experience it is negligible.

As for you, it seems you're having the USB problems i mentioned, cross platform compatibility is yet another thing that makes everything worse, i'd suggest trying different ports, a different adapter and avoiding hubs, if none of it works wifi may be your best choice, you may want to look into a lan adapter for the console.

Closing this as it's a question and not a bug, if you have more questions just reply below.

**Closed by exelix11** 2020-09-28 10:54 UTC
