### ISSUE TITLE
[Bug] Doesn't capture sound of homebrew using audout.

### ISSUE THREAD

**Issue by expandrsps** [exelix11/SysDVR#79] opened 2020-09-06 04:15 UTC
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**
[Running an emulator and capturing it will output video but no sound, not sure if this is a limitation of the applet or a bug with SysDVR]

**To Reproduce**
[Open an emulator (Retroarch) through an app so you are able to capture the screen and start recording, it won't send audio, only sound.]

**Expected behavior**
[It should capture both video and audio]

**Setup information**
 - PC Os: [Windows 10 x64]
 - Console firmware [9.1.0]
 - Custom firmware name and version [Atmosphere 0.14.1]
 - SysDVR version [4.0.1 USB only]

**Additional context**
[Add any other context about the problem here.]

**Comment by expandrsps** [comment] 2020-09-06 05:58
I should say, I think I got applet confused with non-applet, capture works but it doesn't capture audio through USB when using a GBA core on Retroarch

**Comment by exelix11** [comment] 2020-09-06 07:21
> I should say, I think I got applet confused with non-applet, capture works but it doesn't capture audio through USB when using a GBA core on Retroarch

Yeah, applets can't be caputred at all.
I think it's something specific to retroarch as regular games work. 
Do regular games stream audio as expected ? If no your driver setup may be wrong.
Do other retroarch cores or homebrew that play audio stream as expected ? If so it's definitely a retroarch issue.

**Comment by expandrsps** [comment] 2020-09-06 20:41
regular games work, no other cores work on retroarch, nro's dont even work so maybe it's something with homebrew nro files :S

**Comment by exelix11** [comment] 2020-09-06 21:17
Interestingly, seems to be a libnx issue.
I just compiled the [audren](https://github.com/switchbrew/switch-examples/tree/master/audio/audren-simple) and [audout](https://github.com/switchbrew/switch-examples/tree/master/audio/playtone) examples and only sounds produced by the first go through sysdvr.
Don't really have much control on it, will ask to the libnx maintainers, maybe they know the reason.

**Comment by exelix11** [comment] 2020-09-07 08:23
I confirmed the problem is with audout in the current libnx release. On reswitched they told me this has been fixed in libnx master, it may take a bit for it to release and for all homebrew get updated but after that both modes should work.

For this specific case as you (i think ?) already suggested on discord the workaround for retroarch is to set the audio backend to `switch_audren`.

**Closed by exelix11** 2020-09-07 08:23 UTC
