### ISSUE TITLE
[Feature request]  Android client

### ISSUE THREAD

**Issue by mustafapx** [exelix11/SysDVR#122] opened 2021-02-23 07:56 UTC
Is it possible to port the PC client to android ? i know we can stream it to any video player with wifi but the lag is so much about 1.5 sec.
Having an android client to run via usb would make things much accessable as most Tv's nowadays runs android to we can simply plug the switch to the tv via usb and thats it !!.
For Tv's not running android its easy to get a cheap tvbox and use it for that.

**Comment by exelix11** [comment] 2021-02-23 08:58
It's probably possible but I'm not interested in doing it at least for now. 
Let's consider this up for grabs, if anyone is interested in doing it let me know.

**Comment by MAYBreath** [comment] 2021-06-19 17:18
I need it too,please help

**Comment by kanbol** [comment] 2021-06-27 13:52
with this feature,we can stream switch to vr device such as oculus quest.

**Comment by ionn28** [comment] 2021-08-19 21:32
With this feature it would be possible to stream Switch to smart tvs or android tv boxes. I do hope this will be implemented eventually...

**Comment by a2013544516** [comment] 2022-02-24 03:44
Hello, my English is not very good, let me tell you briefly 
I think this Android side is of great significance for carrying out, and I hope that you can implement this project. After all, the usb port of the current sysdvr computer client is still problematic for some plug-ins and people with incomplete dll files

**Comment by DarrenWarrenV** [comment] 2022-10-25 16:46
https://play.google.com/store/apps/details?id=com.shenyaocn.android.WebCam

Only app that lets you actually use it with minimal delay. When you setup connection, you have to connect 2/3 times to get the best possible min. delay. Enjoy!

**Comment by sunshine2077** [comment] 2023-02-02 05:32
The protocol of this project used rtsp. So an android video app which includes the function rtsp client maybe works, like VLC，MXPlayer，but there is a strong delay of them.

**Comment by mustafapx** [comment] 2023-02-02 19:33
Im working on an android app works fine over wifi with very little delay im trying to implement the usb method but android usb is more complicated than i thought will see what i can do about it

**Comment by DarrenWarrenV** [comment] 2023-04-17 09:23
There is no need for a new app. I tested almost everything and the only one with the minimal delay (other apps didn't even come close to this) is: https://play.google.com/store/apps/details?id=com.shenyaocn.android.WebCam

**Comment by AKASGaming** [comment] 2023-04-18 12:51
@mustafapx How far did you get with this?

**Comment by DBinK** [comment] 2023-05-06 15:32
yes，Recently, more and more Android tablets are being sold, we need such an app

**Comment by DBinK** [comment] 2023-05-06 15:32
> 这可能是可能的，但至少现在我对这样做不感兴趣。 让我们考虑一下，如果有人有兴趣这样做，请告诉我。

yes，i want it

**Comment by Elias02345** [comment] 2023-06-23 09:05
Please. I need a sysdvr client for android that works with usb so it has no lags or delay but full color of my Tablet with a oled 120hz screen. Please, i need it for vacstion. A mobile switch dock for multiplayer on my tablet. Thank you

**Comment by Asekit** [comment] 2023-06-28 00:59
> It's probably possible but I'm not interested in doing it at least for now. 
> Let's consider this up for grabs, if anyone is interested in doing it let me know. 
> 

l need it，please

**Comment by Victor053** [comment] 2023-06-28 11:06
> It's probably possible but I'm not interested in doing it at least for now. Let's consider this up for grabs, if anyone is interested in doing it let me know.

yeah we definitely need this

**Comment by exelix11** [comment] 2023-06-28 11:12
Look y'all it's pointless to keep asking.
The mobile programming model is stupid, with Android possibly being the worst, so I'm not going to do it.

If someone actually wants to contribute I'm happy to answer any questions on the protocol or implementation but that's about it. 

Stop spamming this issue with "i want it too" or I'll have to lock it.

**Comment by exelix11** [comment] 2023-06-28 12:32
Wdym all the code is already on this github repo....

**Comment by c01dc0ffee** [comment] 2023-06-28 16:53
please help me my dog is sick and he NEEDS this android app

**Comment by exelix11** [comment] 2023-06-28 16:56
Memes are fun, but not when they're spamming my notifications.

i'll unlock this once there's actual content to be posted, if anyone is developing a mobile client just let me know on discord.

**Comment by exelix11** [comment] 2023-08-29 15:43
I'm working on the next version of sysdvr with a new cross platform GUI and android support.

It's still in early stages but i plan on opening a discord thread for it  in the next few weeks as I will be needing testers. When it's up i'll post an announcement.

**Comment by ForDefault** [comment] 2023-09-06 19:54
Can anyone link me the discord? I can not find it posted anywhere on here.

**Comment by exelix11** [comment] 2023-09-13 15:20
The early android builds are now available. You can get them from github actions:
- First get latest sysmodule (not compiatible with previous clients) https://github.com/exelix11/SysDVR/actions/runs/6108630256
- Then the android app https://github.com/exelix11/SysDVR/actions/runs/6174347490
- There's also an updated windows client for the new sysmodule: https://github.com/exelix11/SysDVR/actions/runs/6174191462

Note that this is an early preview and many features are not implemented yet. Don't open github issues to avoid confusion with the current stable version.

For more info you can joing the sysdvr-beta thread on [discord](https://discord.gg/rqU5Tf8)

**Comment by l2cri** [comment] 2023-09-28 11:01
Android client not installed on Android tv uggos x3 with CPU - Amlogic S905X3

**Comment by exelix11** [comment] 2023-09-28 11:03
32bit verisons of android are not supported (and likely neverl will)
Also there is currently a bug with android versions before 10 but will be fixed soon enough.

**Comment by cjinhub** [comment] 2023-12-16 08:27
> 32bit verisons of android are not supported (and likely neverl will)
> Also there is currently a bug with android versions before 10 but will be fixed soon enough.

It’s meaningless if it doesn’t support 32bit. Most TV OS is based on 32bit android.

**Comment by exelix11** [comment] 2023-12-16 08:30
That is unfortunate, but 32 bit android has been discontinued by google. Latest 64bit devices already dropped compatibility support and won't 32bit only apps anymore.

**Comment by cjinhub** [comment] 2023-12-16 15:37
> That is unfortunate, but 32 bit android has been discontinued by google. Latest 64bit devices already dropped compatibility support and won't 32bit only apps anymore.

Is there any chance to support both 32&64?

**Comment by exelix11** [comment] 2023-12-16 15:43
As things stand right now it is not possible because the client app uses dotnet and it only supports 64 bit architectures.

I am aware the android TV situation is not great but it's the best I can do without making a dedicated android rewrite.

As for phones, anything that comes with android 10+ should be compatible, making it a non-issue for mobile users.

**Comment by cjinhub** [comment] 2023-12-17 04:58
> As things stand right now it is not possible because the client app uses dotnet and it only supports 64 bit architectures.
> 
> I am aware the android TV situation is not great but it's the best I can do without making a dedicated android rewrite.
> 
> As for phones, anything that comes with android 10+ should be compatible, making it a non-issue for mobile users.

It is really a bad news to those NS lite users, they don’t have HDMI port on it. That’s why they like you and your sysdvr very much, but now they can use sysdvr only on desktop devices, then HDMI output on TV.

**Comment by exelix11** [comment] 2023-12-17 10:39
I know. Consider that everything that is not windows nor Linux is best effort support from me since I don't have macs or android tvs. 
The current releases are only possible because of people from the community who do the tests I ask for.

If someone really wanted proper android TV support for old devices, they would have to make a client from scratch that works just on those.

There is a reason I'm trying to keep a single code base and it's that live decoding of video is painfully difficult to get right (and one could argue I'm not even doing it the right way on each platform). Which is why I won't go out of my way to make a special version for a platform I can't even commit to support.

**Comment by DevanWolf** [comment] 2023-12-19 11:22
> * Then the android app https://github.com/exelix11/SysDVR/actions/runs/6174347490
Your download has expired.

**Comment by exelix11** [comment] 2023-12-19 11:23
Scroll the CI runs to find latest one, make sure to get matching sysmodule/client builds.

**Comment by DevanWolf** [comment] 2023-12-20 00:25
> Scroll the CI runs to find latest one, make sure to get matching sysmodule/client builds.

Can't find it, I told you it expired.

**Comment by DevanWolf** [comment] 2024-01-02 03:22
Tried it on Quest 2, confirmed not working.

**Comment by exelix11** [comment] 2024-01-02 09:24
Probably wrong version, if the app launches at all it means the phone has a supported cpu.

**Comment by exelix11** [comment] 2024-01-05 15:05
The android release is now out of beta as part of the 6.0 release ~(that is, in the stability limits you can expect from my releases)~

**Closed by exelix11** 2024-01-05 15:05 UTC
Labels: todo
