### ISSUE TITLE
[Help] ge the next error help pliss mpv not start

### ISSUE THREAD

**Issue by sakuleo** [exelix11/SysDVR#73] opened 2020-07-22 03:01 UTC
el mpv not start  for this error Unhandled exception. System.Net.Sockets.SocketException (10013)

SysDVR-Client - 4.0.1 by exelix
https://github.com/exelix11/SysDVR

Starting stream, press return to stop
If the stream lags try pausing and unpausing the player.
Unhandled exception. System.Net.Sockets.SocketException (10013): Intento de acceso a un socket no permitido por sus permisos de acceso.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at SysDVRClient.RTSP.RtspServer.StartListenerThread()
   at SysDVRClient.RTSP.SysDvrRTSPManager.Begin()
   at SysDVRClient.Program.StartStreaming(BaseStreamManager Streams)
   at SysDVRClient.Program.Main(String[] args)

**Setup information**
 - PC OS: windows 10
 - Console firmware [e.g. 10.1.0]
 - Custom firmware name and version [e.g. Atmosphere ???]
 - SysDVR version [e.g. 4.01 Usb-Only]

**Comment by exelix11** [comment] 2020-07-22 07:55
Duplicate of #71, read the answers and continue the discussion there

**Closed** 2020-07-22 07:55 UTC
